In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

from  sklearn.metrics  import accuracy_score

In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
df = pd.read_csv("DatasetFinal.csv")
df

,Unnamed: 0,Gender,TravelMethod,TravelTime,PartTimeJob,Relationship,Father's_education,Mother's_education,StudyHours,AttendenceLecs,Concentrate,Friends,SocialMediaTime,extra curricular,HowYouPrepare,StudyPattern,Rate yourself,Marks
0,0,1,1,3,0,0,1,1,2,1,1,1,3,1,4,1,1,80 to 89
1,1,1,0,3,0,1,1,2,3,1,1,1,2,1,4,1,1,80 to 89
2,2,1,1,4,0,0,3,2,2,2,1,0,3,0,1,2,3,60 to 69
3,3,1,0,3,0,1,1,2,4,1,1,1,2,1,4,1,1,80 to 89
4,4,1,1,2,0,0,2,1,2,2,1,0,4,0,1,2,2,70 to 79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373,373,0,0,1,0,0,1,2,1,2,1,1,3,0,1,2,1,90 to 100
374,374,1,1,4,1,1,1,2,4,2,1,1,1,1,5,1,1,90 to 100
375,375,1,1,3,0,0,2,2,3,2,1,1,2,1,7,1,1,90 to 100
376,376,1,0,1,1,1,2,2,2,1,1,1,2,1,7,1,1,90 to 100
377,377,1,1,4,1,1,1,2,4,2,1,1,1,1,5,1,1,90 to 100

In [36]:
# df = df.drop(["Gender","TravelMethod","TravelTime","PartTimeJob","Relationship","Father's_education","Mother's_education","StudyHours","AttendenceLecs","Concentrate","Friends","SocialMediaTime","extra curricular","HowYouPrepare","StudyPattern","Rate yourself"], axis=1)
x = df.drop("Marks", axis=1)
y = df["Marks"]

In [37]:
model = RandomForestClassifier()

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

model.fit(x_train, y_train)

RandomForestClassifier()

In [38]:
model.score(x_train,y_train)

1.0

In [39]:
model.score(x_test,y_test)

0.8157894736842105